### ISSUE TITLE
import  error

### ISSUE THREAD

**Issue by codeHui** [krislankford/nativescript-mqtt#1]
I code only "import { MQTTClient } from 'nativescript-mqtt';"there is a error:
I use Version 2.2.1,it matter?

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.Mqtt/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed
SyntaxError: Unexpected token import
File: "<unknown>, line: 1, column: 265
StackTrace: 
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'global.loadModule', file:'/data/data/org.nativescript.Mqtt/files/app/tns_modules/globals/globals.js', line: 29, column: 31
    Frame: function:'resolvePageFromEntry', file:'/data/data/org.nativescript.Mqtt/files/app/tns_modules/ui/frame/frame-common.js', line: 79, column: 40
    Frame: function:'Frame.navigate', file:'/data/data/org.nativescript.Mqtt/files/app/tns_modules/ui/frame/frame-common.js', line: 165, column: 20
    Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/org.nativescript.Mqtt/files/app/tns_modules/ui/frame/frame.js', line: 690, column: 19

**Comment by codeHui** [comment]
I code in ts file,import seems not have error;
but added a similar error
"var client  = new MQTTClient({
  host: 'test.xxxx.cc',
      port: 22222
});"
still Version 2.2.1;
    "tns-android": {
      "version": "2.2.0"
    }
  },
  "dependencies": {
    "tns-core-modules": "2.2.1"
  },
  "devDependencies": {
    "babel-traverse": "6.15.0",
    "babel-types": "6.15.0",
    "babylon": "6.9.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.0",
    "typescript": "^1.8.10"
  }

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.mqttts/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
File: "<unknown>, line: 1, column: 265
StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.mqttts/files/app/tns_modules/nativescript-mqtt/index.js', line: 3, column: 12
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.mqttts/files/app/main-page.js', line: 3, column: 27
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'/data/data/org.nativescript.mqttts/files/app/tns_modules/globals/globals.js', line: 29, column: 31
	Frame: function:'resolvePageFromEntry', file:'/data/data/org.nativescript.mqttts/files/app/tns_modules/ui/frame/frame-common.js', line: 79, column: 40
	Frame: function:'Frame.navigate', file:'/data/data/org.nativescript.mqttts/files/app/tns_modules/ui/frame/frame-common.js', line: 165, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/org.nativescript.mqttts/files/app/tns_modules/ui/frame/frame.js', line: 690, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/org.nativescript.mqttts/files/app/tns_modules/ui/frame/activity.js', line: 12, column: 25

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2457)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2519)
	at android.app.ActivityThread.access$1200(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5669)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

**Comment by codeHui** [comment]
maybe not the version,I tried 2.0l0,the same,

**Comment by codeHui** [comment]
I add "use strict" and var MQTT ，now the error disappear

**Comment by krislankford** [comment]
@codeHui I used this library with TypeScript so the 'use strict' was always in place and had not tested without it. Glad you were able to get it to work. I also see that you are using a custom port. Did that work for you as I have not tried anything outside of http/https.

**Comment by codeHui** [comment]
@krislankford my actual port is 52184;the connected was always failed;just use
[[[var client  = new MQTTClient({
  host: "test.xxxxxx.cc",port: 52184
});
client.connect("xxxxx_mq", "MQ168@xxxxx");]]]

and the err(onFailure: (err: any) => {...}) is
errorCode:7
errorMessage:"AMQJS0007E Socket error:undefined."
invocationContext:undefined

can you see something ? now I just stoped here. and the "nativescript-websockets" is well added.

I am not sure to understand "port" and "http/https",could be specific?"test.xxxxxx.cc:52184" or  "ws://test.xxxxxx.cc:52184"is a websocket uri,you mean in your project,you didn't use "new Websocket()",even without "nativescript-websockets" it will work? 
and http/https can do mqtt,not as I know mqtt over websocket now,is this understand right?

if that ,then "nativescript-websockets" maybe not completely the same with the brower websockets,I think
thanks very much

**Comment by codeHui** [comment]
![qq 20160914112659](https://cloud.githubusercontent.com/assets/17940498/18499190/4dfbf472-7a6f-11e6-9951-4ede6523187d.jpg)

whether  use a custom port,in mqttws.js,it will do like the pic show,I don't know the diff,could give me more advices,I think I am not surely understand,thanks

**Comment by codeHui** [comment]
I found the errorCode:7 is because websocket failed to be opened;
in my test,the same code of 'new WebSocket("ws://testv2.xxxxxx.cc:52184/mqtt", ["mqtt"]);',that can open on brower,but failed in "nativescript-websockets",
don't know way,the api  shows it support this,I tried 'new WebSocket("ws://xxxxxxx")',this is ok in "nativescript-websockets"
