### ISSUE TITLE
Calling publish method with QoS > 0 throws error

### ISSUE THREAD

**Issue by JScearcy** [krislankford/nativescript-mqtt#10]
Publishing using qos > 0 will throw an error due to the localstorage calls - localstorage is set as a Map initially in lieu of the browser's local storage, but then it is called using localstorage.setItem / localstorage.getItem / localstorage.removeItem (localStorage api) 
These will need to be updated with the map equivalent Map.set, Map.get, Map.delete function calls, respectively, to support qos > 0 when publishing.

**Comment by LauraNavarroGalvan** [comment]
same issue

**Comment by edusperoni** [comment]
fixed in nativescript-mqtt-new :)
