### ISSUE TITLE
Can't connect to broker (hivemq)

### ISSUE THREAD

**Issue by spierala** [krislankford/nativescript-mqtt#12]
I am trying to connect to a broker on Android (simulator), but it does not work.

This is the code:
```
    mqtt_host: string = "broker.hivemq.com";
    mqtt_port: number = 8000;
    mqtt_username: string = "";
    mqtt_password: string = "";

    mqtt_clientOptions = {
        host: this.mqtt_host,
        port: this.mqtt_port,
        clientId: 'clientId'
    };

    mqtt_client: MQTTClient = new MQTTClient(this.mqtt_clientOptions);

    constructor() {
        this.setupHandlers();
        this.connect();
    }

    connect() : void {
        try{
            this.mqtt_client.connect(this.mqtt_username, this.mqtt_password);
        }
        catch (e) {
            console.log("Caught error: " + e);
        }
    }

    setupHandlers() : void {
        this.mqtt_client.onConnectionFailure.on((err) => {
            console.log("Connection failed: " + err);
        });

        this.mqtt_client.onConnectionSuccess.on(() => {
            console.log("Connected successfully!");
        });

        this.mqtt_client.onConnectionLost.on((err) => {
            console.log("Connection lost: " + err);
        });
    }
```

After some seconds the console shows:
`JS: Connection failed: undefined`

I also tried other brokers with the same result.

The strange thing is that the same connection details work just fine when using Paho JS Lib in the browser:
```
        <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
        <script>
            // Create a client instance
            client = new Paho.MQTT.Client('broker.hivemq.com', 8000, "clientId");

            client.connect({
                onSuccess: onConnect
            });

            function onConnect() {
                console.log("onConnect"); //works
            }
        </script>
```

Do you have an idea what could be wrong?
Thanks in advance for any help.

**Comment by spierala** [comment]
I activated the trace function of the Client and could see these logs:
```

""Client.connect"{"userName":"","password":"******","useSSL":false,"keepAliveInterval":60,"mqttVersionExplicit":false,"mqttVersion":4,"cleanSession":true}false"
""Client._socket_send"{"type":1,"userName":"","password":"******","useSSL":false,"keepAliveInterval":60,"mqttVersionExplicit":false,"mqttVersion":4,"cleanSession":true,"clientId":"clientId"}"
""Client._disconnected"8"AMQJS0008I Socket closed.""
""Failed to connect V4, dropping back to V3""
""Client._socket_send"{"type":1,"userName":"","password":"******","useSSL":false,"keepAliveInterval":60,"mqttVersionExplicit":false,"mqttVersion":3,"cleanSession":true,"clientId":"clientId"}"
""Client._on_socket_message"{}"
""Client._disconnected"1"AMQJSC0001E Connect timed out.""
```

**Comment by spierala** [comment]
I made some progress... :)
Funny enough the `onConnectionSuccess` callback is called when testing on iPad which is connected to the 3G of my phone's shared internet.

When the iPad is connected to the Wifi then the `onConnectionSuccess` callback is never called but somehow the connection is made successfully anyway and I can publish to the broker. (There is some small hacking of the plugin needed to be able to publish - see this issue: https://github.com/krislankford/nativescript-mqtt/issues/8)

Same with iPad Simulator.

Android Simulator on Win10: `onConnectionSuccess` callback not called, not able to publish.

**Comment by edusperoni** [comment]
I'm having the same problem. Did you ever manage to get this to work?

It seems it's not receiving a "CONNACK". maybe it's a problem with nativescript-websockets?

In my testing, it sends the v4 info and receives an empty message. I've tried manually adding a CONNACK, but none of the subscriptions work, and eventually it receives a Ping Timeout.

**Comment by edusperoni** [comment]
Ok, I managed to get this working. It seems nativescript-websockets is returning the wrong type of message (see https://github.com/NathanaelA/nativescript-websockets/issues/48).

I managed to connect by converting every data to a Int8Array:
```
    ClientImpl.prototype._on_socket_message = function(event) {
       var message = event.data;
       var intarray = new Int8Array(message.remaining());
        var i = 0;
        while(message.remaining()) {
            intarray[i] = message.get();
            i++;
        }
        event.data = intarray.buffer;
```


This made everything work as it should. This is a nativescript-websockets issue.

**Comment by LauraNavarroGalvan** [comment]
For me works:
- updating nativescript-websocket to v1.5.0 
- downloading the plugin nativescript-mqtt and replacing it on the nodes_modules folder, due to when I installed the plugin doesn't download the current changes of the plugin.
