### ISSUE TITLE
How to use this plugin with nativescript + Angular 2?

### ISSUE THREAD

**Issue by Chris81T** [krislankford/nativescript-mqtt#3]
Howdy,
actually I want to develop an android application using Nativescript in Combination with Angular 2. For this app I need a Mqtt Client to subscribe/publish to a Mqtt Broker.

So I found this plugin :-) But sadly there is no documentation like "Getting Started" available to see, how it works.

What I have done:
1. Create with "tns create... --ng" a new project.
2. Integrate this plugin using the command "npm install nativescript-mqtt --save-dev"

My app.component.ts looks like:

`
import {Component} from "@angular/core";

import { MQTTClient } from "nativescript-mqtt/index";

import {SampleComponent} from "./sample/sample.component";

@Component({
    selector: "my-app",
    templateUrl: "app.component.html"
})
export class AppComponent {
    public counter: number = 6;

```
public title: string = "This is a tiny title";

public get message(): string {
    if (this.counter > 0) {
        return this.counter + " taps left";
    } else {
        return "Hoorraaay! \nYou are ready to start building!";
    }
}

public onTap() {
    this.counter--;
}

public sendMqttMessage() {

    let mqttClient = new MQTTClient({
        host: "tcp://broker.hivemq.com",
        port: 1883
    });

    console.log("About to connect mqtt client = ", mqttClient);

    mqttClient.connect("", "");

    console.log("Mqtt client is connected");
}
```

}
`
1. If I will execute with "tns run android --emulator", it will be successfully uploaded to the emulator, but inside the emulator (running the app) it will fail.

This is the output given by the emulator (sorry, that I can only give a snapshot - copy to clipboard does not work):
[https://ibin.co/2wAz3I4KqvlE.png](https://ibin.co/2wAz3I4KqvlE.png)

It would be great, if you can describe shortly, what is to do, to get it with Nativescript+Angular2 running :-)

Thanks!

**Comment by krislankford** [comment]
He @Chris81T - I have not had time to look at this issue. I made this mqtt library some time ago so I would have to go back and look at the code. FYI - this library uses the MQTT protocol over websockets HTTP/HTTPS, not over TCP ports. So if you are trying to connect to a server running MQTT on port 1883/TCP, it won't work. You need to specify only the host name in the host "broker.hivemq.com" and the port should be the endpoint for a websocket not a tcp port. If you are expecting SSL please set that to true in the settings.

**Comment by simeonvk** [comment]
I have the same issue. I have no success to connect to mqtt broker via websocket. I try
test.mosquitto.org on port 8080
broker.hivemq.com on port 8000
iot.eclipse.org on port 80 and path /ws

I changed mqttClient variable to public and add some callbacks for onSuccess and onFailure events.

Everytime, when i try to connect to ws i receive that error: Error code 8 and Error message  AMQJS0008I Socket closed.

This plugin has dependency from nativescript-websockets. Can there is some major changes in current version of websocket plugin, that makes it incompatible with nativescipt-mqtt?

**Comment by krislankford** [comment]
I haven't worked on MQTT/IOT stuff for over year but what I do know is ...

There is a dependency on the nativescript-websockets for this mqtt library. The underlying implementation for MQTT is the paho javascript library located here - https://github.com/eclipse/paho.mqtt.javascript. I looked up the error code and it is SOCKET_CLOSE: {code:8, text:"AMQJS0008I Socket closed."}. One of the problems you'll face is that iOS does not allow http by default so you'd have to connect using https to the endpoint. I'd try to connect to http://test.mosquitto.org/ using port 8081 for secure web sockets. If you want to use plain http you need to configure App Transport Security (ATS). Here's an article - https://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/. Good luck.
