### ISSUE TITLE
Latest version not on npm

### ISSUE THREAD

**Issue by VeeTeeDev** [krislankford/nativescript-mqtt#7]
There is an difference between the repo and the version on NPM (although it's already 6 months old).
Is it possible to (re) publish ?
It's not much, but the import (ClientOptions) is not working since it's not available on the npm version.

**Comment by ejsuncy** [comment]
Yeah--I was recently given rights to publish to npm for this repo but haven't had a chance to actually do it yet. I'll try and check it out after work today!

**Comment by VeeTeeDev** [comment]
That would be awesome, but there's no hurry. I guess it's only the definition so...

**Comment by spierala** [comment]
The version on npm still seems to be outdated. Any progress on it?

**Comment by edusperoni** [comment]
Please try nativecript-mqtt-new. I'm maintaining it for now.

Main changes:

- Up to date with nativescript-mqtt master
- Disconnect method implemented
- paho-mqtt updated to latest version

**Comment by edusperoni** [comment]
@krislankford if you don't plan on doing it anymore, we're using it in production so we'll probably keep maintaining it for a while

**Comment by krislankford** [comment]
@edusperoni - I’m not actively maintaining this anymore so more than happy to transfer ownership. Which account or organization should I transfer this too? Seems like the right thing to do instead of making a new fork. LMK.
