### ISSUE TITLE
publish -> send not working

### ISSUE THREAD

**Issue by VeeTeeDev** [krislankford/nativescript-mqtt#8]
```
import { Message } from "nativescript-mqtt/common";
....
let message: Message = new Message( {
            payload: myPayload,
            topic: myMqttSendTopic,
            bytes: null,
            qos: 0
        });
....
this.mqttClient.publish(message);

....
```
This fails with error 'ERROR Error: Uncaught (in promise): Error: Invalid argument:object'

the line:
 if (!(topic instanceof Message) && (typeof topic !== "string"))
is validating to true and the error is thrown.

but topic = message which is Message from "nativescript-mqtt/common"

Am I missing something ?
Do you have an example ready with this publish/send method working ?

**Comment by ejsuncy** [comment]
I encountered this as well; I thought it was related to some changes I made, but it turns out that publishing never worked in the first place. I've been working on a solution in my spare time. I hope to have some more time this week to implement it.

**Comment by VeeTeeDev** [comment]
Ok,
So you want 2 options there ? Or you pass in a Message, or you pass in all properties (payload, bytes, topic, ...)

**Comment by ejsuncy** [comment]
The cause is that the Message class provided by this plugin doesn't have in its prototype chain the prototype of the Paho library's own Message class (function). The issue I'm working on right now is that iOS 11 has some buggy behavior with NativeScript, so I'm trying to work around that.

**Comment by JScearcy** [comment]
I created a quick work around for this issue just creating an MQTT.Message out of the current implementation of Message

**Comment by JScearcy** [comment]
I noticed in further testing that publishing using qos beyond 0 will throw an error due to the localstorage calls - localstorage is set to as a Map in lieu of the browser's local storage, but then it is called using localstorage.setItem / localstorage.getItem / localstorage.removeItem - these will need to be updated with the map equivalent Map.set, Map.get, Map.delete function calls, respectively, to support higher qos when publishing.

**Comment by ejsuncy** [comment]
Thanks--could you open a new issue with that description?
